In [19]:
import pandas as pd
import numpy as np
import os
import shutil
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_json('transactions.txt', lines=True)

In [21]:
df.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,...,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud
0,737265056,737265056,5000,5000.0,2016-08-13T14:27:32,98.55,Uber,US,US,02,...,,0.0,,,,False,,,False,False
1,737265056,737265056,5000,5000.0,2016-10-11T05:05:54,74.51,AMC #191138,US,US,09,...,,0.0,,,,True,,,False,False
2,737265056,737265056,5000,5000.0,2016-11-08T09:18:39,7.47,Play Store,US,US,09,...,,0.0,,,,False,,,False,False
3,737265056,737265056,5000,5000.0,2016-12-10T02:14:50,7.47,Play Store,US,US,09,...,,0.0,,,,False,,,False,False
4,830329091,830329091,5000,5000.0,2016-03-24T21:04:46,71.18,Tim Hortons #947751,US,US,02,...,,0.0,,,,True,,,False,False

In [22]:
df.columns.to_list()

['accountNumber',
 'customerId',
 'creditLimit',
 'availableMoney',
 'transactionDateTime',
 'transactionAmount',
 'merchantName',
 'acqCountry',
 'merchantCountryCode',
 'posEntryMode',
 'posConditionCode',
 'merchantCategoryCode',
 'currentExpDate',
 'accountOpenDate',
 'dateOfLastAddressChange',
 'cardCVV',
 'enteredCVV',
 'cardLast4Digits',
 'transactionType',
 'echoBuffer',
 'currentBalance',
 'merchantCity',
 'merchantState',
 'merchantZip',
 'cardPresent',
 'posOnPremises',
 'recurringAuthInd',
 'expirationDateKeyInMatch',
 'isFraud']

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786363 entries, 0 to 786362
Data columns (total 29 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   accountNumber             786363 non-null  int64
 1   customerId                786363 non-null  int64
 2   creditLimit               786363 non-null  int64
 3   availableMoney            786363 non-null  float64
 4   transactionDateTime       786363 non-null  object
 5   transactionAmount         786363 non-null  float64
 6   merchantName              786363 non-null  object
 7   acqCountry                786363 non-null  object
 8   merchantCountryCode       786363 non-null  object
 9   posEntryMode              786363 non-null  object
 10  posConditionCode          786363 non-null  object
 11  merchantCategoryCode      786363 non-null  object
 12  currentExpDate            786363 non-null  object
 13  accountOpenDate           786363 non-null  object
 14  dateOfLastAddressChange   786363 non-null  object
 15  cardCVV                   786363 non-null  int64
 16  enteredCVV                786363 non-null  int64
 17  cardLast4Digits           786363 non-null  int64
 18  transactionType           786363 non-null  object
 19  echoBuffer                786363 non-null  object
 20  currentBalance            786363 non-null  float64
 21  merchantCity              786363 non-null  object
 22  merchantState             786363 non-null  object
 23  merchantZip               786363 non-null  object
 24  cardPresent               786363 non-null  bool
 25  posOnPremises             786363 non-null  object
 26  recurringAuthInd          786363 non-null  object
 27  expirationDateKeyInMatch  786363 non-null  bool
 28  isFraud                   786363 non-null  bool
dtypes: bool(3), float64(3), int64(6), object(17)
memory usage: 158.2+ MB

In [24]:
df.columns

Index(['accountNumber', 'customerId', 'creditLimit', 'availableMoney',
       'transactionDateTime', 'transactionAmount', 'merchantName',
       'acqCountry', 'merchantCountryCode', 'posEntryMode', 'posConditionCode',
       'merchantCategoryCode', 'currentExpDate', 'accountOpenDate',
       'dateOfLastAddressChange', 'cardCVV', 'enteredCVV', 'cardLast4Digits',
       'transactionType', 'echoBuffer', 'currentBalance', 'merchantCity',
       'merchantState', 'merchantZip', 'cardPresent', 'posOnPremises',
       'recurringAuthInd', 'expirationDateKeyInMatch', 'isFraud'],
      dtype='object')

In [28]:
df['acqCountry'].unique()

array(['US', '', 'CAN', 'MEX', 'PR'], dtype=object)

In [29]:
df['acqCountry'].value_counts()

US     774709
         4562
MEX      3130
CAN      2424
PR       1538
Name: acqCountry, dtype: int64

In [31]:
df['cardLast4Digits'].nunique()

5245

In [33]:
# This should be dropped.

df['echoBuffer'].unique()

array([''], dtype=object)

In [34]:
df['merchantCountryCode'].value_counts()

US     778511
MEX      3143
CAN      2426
PR       1559
          724
Name: merchantCountryCode, dtype: int64

In [35]:
df['merchantCountryCode'].head()

0    US
1    US
2    US
3    US
4    US
Name: merchantCountryCode, dtype: object

In [36]:
df['merchantCategoryCode'].head()

0        rideshare
1    entertainment
2       mobileapps
3       mobileapps
4         fastfood
Name: merchantCategoryCode, dtype: object

In [39]:
df['merchantCategoryCode'].unique()

array(['rideshare', 'entertainment', 'mobileapps', 'fastfood',
       'food_delivery', 'auto', 'online_retail', 'gym', 'health',
       'personal care', 'food', 'fuel', 'online_subscriptions',
       'online_gifts', 'hotels', 'airline', 'furniture', 'subscriptions',
       'cable/phone'], dtype=object)

In [38]:
df['merchantCategoryCode'].describe()

count            786363
unique               19
top       online_retail
freq             202156
Name: merchantCategoryCode, dtype: object

In [41]:
df.columns

Index(['accountNumber', 'customerId', 'creditLimit', 'availableMoney',
       'transactionDateTime', 'transactionAmount', 'merchantName',
       'acqCountry', 'merchantCountryCode', 'posEntryMode', 'posConditionCode',
       'merchantCategoryCode', 'currentExpDate', 'accountOpenDate',
       'dateOfLastAddressChange', 'cardCVV', 'enteredCVV', 'cardLast4Digits',
       'transactionType', 'echoBuffer', 'currentBalance', 'merchantCity',
       'merchantState', 'merchantZip', 'cardPresent', 'posOnPremises',
       'recurringAuthInd', 'expirationDateKeyInMatch', 'isFraud'],
      dtype='object')

In [74]:
for i in df.columns:
    
    print(f'{i} = \n {df[i].describe()}\n')

accountNumber =
 count    7.863630e+05
mean     5.372326e+08
std      2.554211e+08
min      1.000881e+08
25%      3.301333e+08
50%      5.074561e+08
75%      7.676200e+08
max      9.993896e+08
Name: accountNumber, dtype: float64

customerId =
 count    7.863630e+05
mean     5.372326e+08
std      2.554211e+08
min      1.000881e+08
25%      3.301333e+08
50%      5.074561e+08
75%      7.676200e+08
max      9.993896e+08
Name: customerId, dtype: float64

creditLimit =
 count    786363.000000
mean      10759.464459
std       11636.174890
min         250.000000
25%        5000.000000
50%        7500.000000
75%       15000.000000
max       50000.000000
Name: creditLimit, dtype: float64

availableMoney =
 count    786363.000000
mean       6250.725369
std        8880.783989
min       -1005.630000
25%        1077.420000
50%        3184.860000
75%        7500.000000
max       50000.000000
Name: availableMoney, dtype: float64

transactionDateTime =
 count                  786363
unique                 776637
top       2016-12-25T14:04:15
freq                        4
Name: transactionDateTime, dtype: object

transactionAmount =
 count    786363.000000
mean        136.985791
std         147.725569
min           0.000000
25%          33.650000
50%          87.900000
75%         191.480000
max        2011.540000
Name: transactionAmount, dtype: float64

merchantName =
 count     786363
unique      2490
top         Uber
freq       25613
Name: merchantName, dtype: object

acqCountry =
 count     786363
unique         5
top           US
freq      774709
Name: acqCountry, dtype: object

merchantCountryCode =
 count     786363
unique         5
top           US
freq      778511
Name: merchantCountryCode, dtype: object

posEntryMode =
 count     786363
unique         6
top           05
freq      315035
Name: posEntryMode, dtype: object

posConditionCode =
 count     786363
unique         4
top           01
freq      628787
Name: posConditionCode, dtype: object

merchantCategoryCode =
 count            786363
unique               19
top       online_retail
freq             202156
Name: merchantCategoryCode, dtype: object

currentExpDate =
 count      786363
unique        165
top       03/2029
freq         5103
Name: currentExpDate, dtype: object

accountOpenDate =
 count         786363
unique          1820
top       2014-06-21
freq           33623
Name: accountOpenDate, dtype: object

dateOfLastAddressChange =
 count         786363
unique          2184
top       2016-03-15
freq            3819
Name: dateOfLastAddressChange, dtype: object

cardCVV =
 count    786363.000000
mean        544.467338
std         261.524220
min         100.000000
25%         310.000000
50%         535.000000
75%         785.000000
max         998.000000
Name: cardCVV, dtype: float64

enteredCVV =
 count    786363.000000
mean        544.183857
std         261.551254
min           0.000000
25%         310.000000
50%         535.000000
75%         785.000000
max         998.000000
Name: enteredCVV, dtype: float64

cardLast4Digits =
 count    786363.000000
mean       4757.417799
std        2996.583810
min           0.000000
25%        2178.000000
50%        4733.000000
75%        7338.000000
max        9998.000000
Name: cardLast4Digits, dtype: float64

transactionType =
 count       786363
unique           4
top       PURCHASE
freq        745193
Name: transactionType, dtype: object

echoBuffer =
 count     786363
unique         1
top
freq      786363
Name: echoBuffer, dtype: object

currentBalance =
 count    786363.000000
mean       4508.739089
std        6457.442068
min           0.000000
25%         689.910000
50%        2451.760000
75%        5291.095000
max       47498.810000
Name: currentBalance, dtype: float64

merchantCity =
 count     786363
unique         1
top
freq      786363
Name: merchantCity, dtype: object

merchantState =
 count     786363
unique         1
top
freq      786363
Name: merchantState, dtype: object

merchantZip =
 count     786363
unique         1
top
freq      786363
Name: merchantZip, dtype: object

cardPresent =
 count     786363
unique         2
top        False
freq      433495
Name: cardPresent, dtype: object

posOnPremises =
 count     786363
unique         1
top
freq      786363
Name: posOnPremises, dtype: object

recurringAuthInd =
 count     786363
unique         1
top
freq      786363
Name: recurringAuthInd, dtype: object

expirationDateKeyInMatch =
 count     786363
unique         2
top        False
freq      785320
Name: expirationDateKeyInMatch, dtype: object

isFraud =
 count     786363
unique         2
top        False
freq      773946
Name: isFraud, dtype: object

In [71]:
# Using lambda functions

list(map(lambda x: df[x].describe(), df.columns))

[count    7.863630e+05
 mean     5.372326e+08
 std      2.554211e+08
 min      1.000881e+08
 25%      3.301333e+08
 50%      5.074561e+08
 75%      7.676200e+08
 max      9.993896e+08
 Name: accountNumber, dtype: float64,
 count    7.863630e+05
 mean     5.372326e+08
 std      2.554211e+08
 min      1.000881e+08
 25%      3.301333e+08
 50%      5.074561e+08
 75%      7.676200e+08
 max      9.993896e+08
 Name: customerId, dtype: float64,
 count    786363.000000
 mean      10759.464459
 std       11636.174890
 min         250.000000
 25%        5000.000000
 50%        7500.000000
 75%       15000.000000
 max       50000.000000
 Name: creditLimit, dtype: float64,
 count    786363.000000
 mean       6250.725369
 std        8880.783989
 min       -1005.630000
 25%        1077.420000
 50%        3184.860000
 75%        7500.000000
 max       50000.000000
 Name: availableMoney, dtype: float64,
 count                  786363
 unique                 776637
 top       2016-12-25T14:04:15
 freq                        4
 Name: transactionDateTime, dtype: object,
 count    786363.000000
 mean        136.985791
 std         147.725569
 min           0.000000
 25%          33.650000
 50%          87.900000
 75%         191.480000
 max        2011.540000
 Name: transactionAmount, dtype: float64,
 count     786363
 unique      2490
 top         Uber
 freq       25613
 Name: merchantName, dtype: object,
 count     786363
 unique         5
 top           US
 freq      774709
 Name: acqCountry, dtype: object,
 count     786363
 unique         5
 top           US
 freq      778511
 Name: merchantCountryCode, dtype: object,
 count     786363
 unique         6
 top           05
 freq      315035
 Name: posEntryMode, dtype: object,
 count     786363
 unique         4
 top           01
 freq      628787
 Name: posConditionCode, dtype: object,
 count            786363
 unique               19
 top       online_retail
 freq             202156
 Name: merchantCategoryCode, dtype: object,
 count      786363
 unique        165
 top       03/2029
 freq         5103
 Name: currentExpDate, dtype: object,
 count         786363
 unique          1820
 top       2014-06-21
 freq           33623
 Name: accountOpenDate, dtype: object,
 count         786363
 unique          2184
 top       2016-03-15
 freq            3819
 Name: dateOfLastAddressChange, dtype: object,
 count    786363.000000
 mean        544.467338
 std         261.524220
 min         100.000000
 25%         310.000000
 50%         535.000000
 75%         785.000000
 max         998.000000
 Name: cardCVV, dtype: float64,
 count    786363.000000
 mean        544.183857
 std         261.551254
 min           0.000000
 25%         310.000000
 50%         535.000000
 75%         785.000000
 max         998.000000
 Name: enteredCVV, dtype: float64,
 count    786363.000000
 mean       4757.417799
 std        2996.583810
 min           0.000000
 25%        2178.000000
 50%        4733.000000
 75%        7338.000000
 max        9998.000000
 Name: cardLast4Digits, dtype: float64,
 count       786363
 unique           4
 top       PURCHASE
 freq        745193
 Name: transactionType, dtype: object,
 count     786363
 unique         1
 top
 freq      786363
 Name: echoBuffer, dtype: object,
 count    786363.000000
 mean       4508.739089
 std        6457.442068
 min           0.000000
 25%         689.910000
 50%        2451.760000
 75%        5291.095000
 max       47498.810000
 Name: currentBalance, dtype: float64,
 count     786363
 unique         1
 top
 freq      786363
 Name: merchantCity, dtype: object,
 count     786363
 unique         1
 top
 freq      786363
 Name: merchantState, dtype: object,
 count     786363
 unique         1
 top
 freq      786363
 Name: merchantZip, dtype: object,
 count     786363
 unique         2
 top        False
 freq      433495
 Name: cardPresent, dtype: object,
 count     786363
 unique         1
 top
 freq      786363
 Name: posOnPremises, dtype: object,
 count     786363
 unique         1
 top
 freq      786363
 Name: recurringAuthInd, dtype: object,
 count     786363
 unique         2
 top        False
 freq      785320
 Name: expirationDateKeyInMatch, dtype: object,
 count     786363
 unique         2
 top        False
 freq      773946
 Name: isFraud, dtype: object]

In [8]:
x = 'accountNumber'

In [9]:
z = lambda y: y[0].upper()+ y[1:]

In [10]:
z(x)

'AccountNumber'

In [11]:
list(map(z, df.columns.to_list()))

['AccountNumber',
 'CustomerId',
 'CreditLimit',
 'AvailableMoney',
 'TransactionDateTime',
 'TransactionAmount',
 'MerchantName',
 'AcqCountry',
 'MerchantCountryCode',
 'PosEntryMode',
 'PosConditionCode',
 'MerchantCategoryCode',
 'CurrentExpDate',
 'AccountOpenDate',
 'DateOfLastAddressChange',
 'CardCVV',
 'EnteredCVV',
 'CardLast4Digits',
 'TransactionType',
 'EchoBuffer',
 'CurrentBalance',
 'MerchantCity',
 'MerchantState',
 'MerchantZip',
 'CardPresent',
 'PosOnPremises',
 'RecurringAuthInd',
 'ExpirationDateKeyInMatch',
 'IsFraud']

In [12]:
df.columns

Index(['accountNumber', 'customerId', 'creditLimit', 'availableMoney',
       'transactionDateTime', 'transactionAmount', 'merchantName',
       'acqCountry', 'merchantCountryCode', 'posEntryMode', 'posConditionCode',
       'merchantCategoryCode', 'currentExpDate', 'accountOpenDate',
       'dateOfLastAddressChange', 'cardCVV', 'enteredCVV', 'cardLast4Digits',
       'transactionType', 'echoBuffer', 'currentBalance', 'merchantCity',
       'merchantState', 'merchantZip', 'cardPresent', 'posOnPremises',
       'recurringAuthInd', 'expirationDateKeyInMatch', 'isFraud'],
      dtype='object')

In [13]:
df.columns = list(map(z, df.columns.to_list()))

In [14]:
df.columns

Index(['AccountNumber', 'CustomerId', 'CreditLimit', 'AvailableMoney',
       'TransactionDateTime', 'TransactionAmount', 'MerchantName',
       'AcqCountry', 'MerchantCountryCode', 'PosEntryMode', 'PosConditionCode',
       'MerchantCategoryCode', 'CurrentExpDate', 'AccountOpenDate',
       'DateOfLastAddressChange', 'CardCVV', 'EnteredCVV', 'CardLast4Digits',
       'TransactionType', 'EchoBuffer', 'CurrentBalance', 'MerchantCity',
       'MerchantState', 'MerchantZip', 'CardPresent', 'PosOnPremises',
       'RecurringAuthInd', 'ExpirationDateKeyInMatch', 'IsFraud'],
      dtype='object')

In [15]:
df

,AccountNumber,CustomerId,CreditLimit,AvailableMoney,TransactionDateTime,TransactionAmount,MerchantName,AcqCountry,MerchantCountryCode,PosEntryMode,...,EchoBuffer,CurrentBalance,MerchantCity,MerchantState,MerchantZip,CardPresent,PosOnPremises,RecurringAuthInd,ExpirationDateKeyInMatch,IsFraud
0,737265056,737265056,5000,5000.00,2016-08-13T14:27:32,98.55,Uber,US,US,02,...,,0.00,,,,False,,,False,False
1,737265056,737265056,5000,5000.00,2016-10-11T05:05:54,74.51,AMC #191138,US,US,09,...,,0.00,,,,True,,,False,False
2,737265056,737265056,5000,5000.00,2016-11-08T09:18:39,7.47,Play Store,US,US,09,...,,0.00,,,,False,,,False,False
3,737265056,737265056,5000,5000.00,2016-12-10T02:14:50,7.47,Play Store,US,US,09,...,,0.00,,,,False,,,False,False
4,830329091,830329091,5000,5000.00,2016-03-24T21:04:46,71.18,Tim Hortons #947751,US,US,02,...,,0.00,,,,True,,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786358,732852505,732852505,50000,48904.96,2016-12-22T18:44:12,119.92,Lyft,US,US,90,...,,1095.04,,,,False,,,False,False
786359,732852505,732852505,50000,48785.04,2016-12-25T16:20:34,18.89,hulu.com,US,US,09,...,,1214.96,,,,False,,,False,False
786360,732852505,732852505,50000,48766.15,2016-12-27T15:46:24,49.43,Lyft,US,US,02,...,,1233.85,,,,False,,,False,False
786361,732852505,732852505,50000,48716.72,2016-12-29T00:30:55,49.89,walmart.com,US,US,09,...,,1283.28,,,,False,,,False,False
786362,732852505,732852505,50000,48666.83,2016-12-30T20:10:29,72.18,Uber,US,US,05,...,,1333.17,,,,False,,,False,False

In [16]:
df.shape

(786363, 29)

In [17]:
df.dtypes

AccountNumber                 int64
CustomerId                    int64
CreditLimit                   int64
AvailableMoney              float64
TransactionDateTime          object
TransactionAmount           float64
MerchantName                 object
AcqCountry                   object
MerchantCountryCode          object
PosEntryMode                 object
PosConditionCode             object
MerchantCategoryCode         object
CurrentExpDate               object
AccountOpenDate              object
DateOfLastAddressChange      object
CardCVV                       int64
EnteredCVV                    int64
CardLast4Digits               int64
TransactionType              object
EchoBuffer                   object
CurrentBalance              float64
MerchantCity                 object
MerchantState                object
MerchantZip                  object
CardPresent                    bool
PosOnPremises                object
RecurringAuthInd             object
ExpirationDateKeyInMatch       bool
IsFraud                        bool
dtype: object

In [18]:
df.nunique()

AccountNumber                 5000
CustomerId                    5000
CreditLimit                     10
AvailableMoney              521915
TransactionDateTime         776637
TransactionAmount            66038
MerchantName                  2490
AcqCountry                       5
MerchantCountryCode              5
PosEntryMode                     6
PosConditionCode                 4
MerchantCategoryCode            19
CurrentExpDate                 165
AccountOpenDate               1820
DateOfLastAddressChange       2184
CardCVV                        899
EnteredCVV                     976
CardLast4Digits               5245
TransactionType                  4
EchoBuffer                       1
CurrentBalance              487318
MerchantCity                     1
MerchantState                    1
MerchantZip                      1
CardPresent                      2
PosOnPremises                    1
RecurringAuthInd                 1
ExpirationDateKeyInMatch         2
IsFraud                          2
dtype: int64